/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Rocketship.glb --transform -t --instance
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import type {ModelProps} from './ModelWrapper'

type GLTFResult = GLTF & {
  nodes: {
    rocket_ship: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
  }
}


export function RocketModel(props: ModelProps) {
  const { nodes, materials } = useGLTF('/Rocketship-transformed.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} ref={props.newRef}>
      <mesh geometry={nodes.rocket_ship.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/Rocketship-transformed.glb')
